#!/usr/bin/env bash
set -e # Exit if one of commands exit with non-zero exit code
set -u # Treat unset variables and parameters other than the special parameters ‘@’ or ‘*’ as an error
set -o pipefail # Any command failed in the pipe fails the whole pipe
# set -x # Print shell commands as they are executed (or you can try -v which is less verbose)

# For some reason media buttons takes ages to respond in Spotify on mac. This script solves the problem for some time. After that
# you may need to rerun the scipt (Fuck Spotify).
# https://www.reddit.com/r/mac/comments/x1ifq9/does_anyone_elses_media_buttons_take_ages_to/

rm -rf ~/Library/Application\ Support/Spotify
