#!/usr/bin/env bash
set -e # Exit if one of commands exit with non-zero exit code
set -u # Treat unset variables and parameters other than the special parameters ‘@’ or ‘*’ as an error
set -o pipefail # Any command failed in the pipe fails the whole pipe
# set -x # Print shell commands as they are executed (or you can try -v which is less verbose)

head=${1:-HEAD}
branch_name=$(git rev-parse --abbrev-ref $head)
if git show-ref -q o/${branch_name}; then
    git merge-base $head o/${branch_name}
    exit 0
fi

echo "Can't find base for $head" > /dev/stderr
exit 1

first_not_my_commit=$(git log --perl-regexp --author='^((?!Nikita Bobko).*)$' -1 --pretty='%H' $head)
if ! [ -z "$first_not_my_commit" ]; then
    echo $first_not_my_commit
    exit 0
fi

