#!/usr/bin/env bash
set -e # Exit if one of commands exit with non-zero exit code
set -u # Treat unset variables and parameters other than the special parameters ‘@’ or ‘*’ as an error
set -o pipefail # Any command failed in the pipe fails the whole pipe
# set -x # Print shell commands as they are executed (or you can try -v which is less verbose)

branch_name=$(git branch --show-current)
if git show-ref -q o/${branch_name}; then
    git l o/${branch_name}~..HEAD "$@"
    exit 0
fi

first_not_my_commit=$(git log --perl-regexp --author='^((?!Nikita Bobko).*)$' -1 --pretty='%H')
if ! [ -z "$first_not_my_commit" ]; then
    git l $first_not_my_commit~..HEAD "$@"
    exit 0
fi

# fallback strategy
git l -10 "$@"
