#!/usr/bin/env bash
set -e # Exit if one of commands exit with non-zero exit code
set -u # Treat unset variables and parameters other than the special parameters ‘@’ or ‘*’ as an error
set -o pipefail # Any command failed in the pipe fails the whole pipe
# set -x # Print shell commands as they are executed (or you can try -v which is less verbose)

if [ ! -t 0 ]; then # If stdin descriptor isn't opened on tty (it can be interpreted as "something is piped into the stdin")
    grep --color=auto --fixed-string --ignore-case -n "$*"
else # Otherwise grep current dir
    grep --color=auto --fixed-string --ignore-case --binary-files=without-match -n -r "$*"
fi
