#!/usr/bin/env bash
set -e # Exit if one of commands exit with non-zero exit code
set -u # Treat unset variables and parameters other than the special parameters ‘@’ or ‘*’ as an error

# "o" stands for "open"

if [ ! -d "$1" ] && [ -x "$1" ]; then
    # The `if` is a replacement for `./executable`. It's not engornomic to type './'

    command="$1"
    shift

    exec ./"$command" "$@"
fi

if isMacOs; then
    open "$@"
else
    detach xdg-open "$@"
fi
