#!/usr/bin/env bash
set -e # Exit if one of commands exit with non-zero exit code
set -u # Treat unset variables and parameters other than the special parameters ‘@’ or ‘*’ as an error
set -o pipefail # Any command failed in the pipe fails the whole pipe
# set -x # Print shell commands as they are executed (or you can try -v which is less verbose)

mkdir -p ${HOME}/.trashBobko
for file in "$@"; do
    if ! [[ "$file" == -* ]]; then # If path doesn't start with "-". E.g. -rf
        to="${HOME}/.trashBobko/$(readlink -f "$file")-REMOVED-$(date +%Y-%m-%d-%H:%M:%S)"
        mkdir -p "$(dirname "$to")"
        mv -- "$file" "$to"
    fi
done
