#!/usr/bin/env bash
set -e # Exit if one of commands exit with non-zero exit code
set -u # Treat unset variables and parameters other than the special parameters ‘@’ or ‘*’ as an error
set -o pipefail # Any command failed in the pipe fails the whole pipe
# set -x # Print shell commands as they are executed (or you can try -v which is less verbose)

buildList() {
    find \
        /Applications \
        ~/Applications/JetBrains\ Toolbox \
        /System/Applications \
        /System/Library/CoreServices \
        /System/Applications/Utilities \
        -maxdepth 1 -name "*.app" | sed -E "s/^(.*)$/open '\1'/"
    find ~/.password-store -name '*.gpg' | sed 's/\.gpg$//' | sed 's/.*password-store\///' | sed 's/^/pass show /'
}

eval "$(buildList | fzf)"
