#!/usr/bin/env bash
set -e # Exit if one of commands exit with non-zero exit code
set -u # Treat unset variables and parameters other than the special parameters ‘@’ or ‘*’ as an error
set -o pipefail # Any command failed in the pipe fails the whole pipe
# set -x # Print shell commands as they are executed (or you can try -v which is less verbose)

echo "Press Enter to stop"
now=$(date +%s)sec
while true; do
    printf "%s\r" $(TZ=UTC date --date now-$now +%H:%M:%S.%N)
    sleep 0.1
done
